name: cityway_report_fm
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.2.1
  intl: ^0.18.1
  get: ^4.6.5
  image_picker: ^1.0.7
  flutter_easyloading: ^3.0.5
  syncfusion_flutter_signaturepad: ^24.2.6
  path_provider: ^2.1.2
  flutter_slidable: ^3.0.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  cached_network_image: ^3.3.1
  socket_io_client: ^2.0.0

  flutter_localizations:
    sdk: flutter
  http: ^1.2.1
  http_parser: ^4.0.2
  flutter_secure_storage: ^9.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  responsive_sizer: 3.3.0+1
  transparent_image: 2.0.1
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  iso: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
